# Generated by Django 4.2.7 on 2025-10-03 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('download_speed', models.CharField(help_text='Download speed limit (e.g., 5M, 10M, 100M)', max_length=20)),
                ('upload_speed', models.CharField(help_text='Upload speed limit (e.g., 5M, 10M, 100M)', max_length=20)),
                ('rate_limit', models.CharField(blank=True, help_text='Combined rate limit (e.g., 5M/5M). Auto-generated if empty.', max_length=50)),
                ('data_limit_mb', models.IntegerField(blank=True, help_text='Total data limit in MB (leave empty for unlimited)', null=True)),
                ('duration_value', models.IntegerField(help_text='Duration value (e.g., 1, 7, 30)')),
                ('duration_unit', models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in your currency (e.g., KES, USD)', max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Show this profile to customers on self-service portal')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_customers', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['is_active', 'is_public'], name='profiles_pr_is_acti_ae1e04_idx'), models.Index(fields=['price'], name='profiles_pr_price_1b8c8a_idx')],
            },
        ),
    ]
