# Generated by Django 4.2.7 on 2025-10-03 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DISABLED', 'Disabled'), ('PENDING', 'Pending Payment')], default='PENDING', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
                ('total_connections', models.IntegerField(default=0)),
                ('data_used_mb', models.BigIntegerField(default=0)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('send_notifications', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='profiles.profile')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='routers.router')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('caller_id', models.CharField(blank=True, max_length=100)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='customers.customer')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routers.router')),
            ],
            options={
                'verbose_name': 'Customer Session',
                'verbose_name_plural': 'Customer Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['customer', '-started_at'], name='customers_c_custome_41cf77_idx'), models.Index(fields=['-started_at'], name='customers_c_started_d44b71_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['username'], name='customers_c_usernam_f90eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['router', 'is_active'], name='customers_c_router__971140_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status', '-created_at'], name='customers_c_status_b0ea05_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['expires_at'], name='customers_c_expires_59eb9b_idx'),
        ),
    ]
